export const data = JSON.parse("{\"key\":\"v-3ad3f8a6\",\"path\":\"/category/JavaScript/13.html\",\"title\":\"数据类型的判断\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"数据类型的判断\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2022-05-23T13:42:00.000Z\",\"category\":[\"JavaScript\"],\"tag\":[\"JavaScript\"],\"description\":\"一、基本数据类型 JS 中七种内置类型（null，undefined，boolean，number，string，symbol，object）又分为两大类型 两大类型： 基本类型：null，undefined,boolean,number,string,symbol 引用类型 Object：Array，Function，Date，RegExp 等 两大基本类型 二、数据类型的判断\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/category/JavaScript/13.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"数据类型的判断\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、基本数据类型 JS 中七种内置类型（null，undefined，boolean，number，string，symbol，object）又分为两大类型 两大类型： 基本类型：null，undefined,boolean,number,string,symbol 引用类型 Object：Array，Function，Date，RegExp 等 两大基本类型 二、数据类型的判断\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"数据类型的判断\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JavaScript\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-05-23T13:42:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"数据类型的判断\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-05-23T13:42:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.42,\"words\":426},\"filePathRelative\":\"category/JavaScript/13.md\",\"localizedDate\":\"2022年5月23日\",\"excerpt\":\"<h2> 一、基本数据类型</h2>\\n<hr>\\n<p>JS 中七种内置类型（null，undefined，boolean，number，string，symbol，object）又分为两大类型</p>\\n<h3> 两大类型：</h3>\\n<ul>\\n<li>基本类型：null，undefined,boolean,number,string,symbol</li>\\n<li>引用类型 Object：Array，Function，Date，RegExp 等</li>\\n</ul>\\n<figure><figcaption>两大基本类型</figcaption></figure>\\n<h2> 二、数据类型的判断</h2>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
