export const data = JSON.parse("{\"key\":\"v-3400962a\",\"path\":\"/category/JavaScript/15.html\",\"title\":\"上拉加载下拉刷新\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"上拉加载下拉刷新\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2022-03-09T11:16:00.000Z\",\"category\":[\"JavaScript\"],\"tag\":[\"JavaScript\"],\"description\":\"上拉加载下拉刷新 一、前言 下拉刷新和上拉加载这两种交互方式通常出现在移动端中 本质上等同于 PC 网页中的分页，只是交互形式不同 开源社区也有很多优秀的解决方案，如 iscroll、better-scroll、pulltorefresh.js 库等等 这些第三方库使用起来非常便捷 我们通过原生的方式实现一次上拉加载，下拉刷新，有助于对第三方库有更好的理解与使用\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/JavaScript/15.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"上拉加载下拉刷新\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"上拉加载下拉刷新 一、前言 下拉刷新和上拉加载这两种交互方式通常出现在移动端中 本质上等同于 PC 网页中的分页，只是交互形式不同 开源社区也有很多优秀的解决方案，如 iscroll、better-scroll、pulltorefresh.js 库等等 这些第三方库使用起来非常便捷 我们通过原生的方式实现一次上拉加载，下拉刷新，有助于对第三方库有更好的理解与使用\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"上拉加载下拉刷新\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JavaScript\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-09T11:16:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"上拉加载下拉刷新\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-03-09T11:16:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":5.22,\"words\":1566},\"filePathRelative\":\"category/JavaScript/15.md\",\"localizedDate\":\"2022年3月9日\",\"excerpt\":\"<figure><figcaption>上拉加载下拉刷新</figcaption></figure>\\n<h2> 一、前言</h2>\\n<hr>\\n<p>下拉刷新和上拉加载这两种交互方式通常出现在移动端中</p>\\n<p>本质上等同于 PC 网页中的分页，只是交互形式不同</p>\\n<p>开源社区也有很多优秀的解决方案，如 <code>iscroll</code>、<code>better-scroll</code>、<code>pulltorefresh.js</code> 库等等</p>\\n<p>这些第三方库使用起来非常便捷</p>\\n<p>我们通过原生的方式实现一次上拉加载，下拉刷新，有助于对第三方库有更好的理解与使用</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
