export const data = JSON.parse("{\"key\":\"v-125db511\",\"path\":\"/category/JavaScript/20.html\",\"title\":\"JavaScript数组的常用方法有哪些\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"JavaScript数组的常用方法有哪些\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2022-03-29T17:12:00.000Z\",\"category\":[\"JavaScript\"],\"tag\":[\"JavaScript\"],\"description\":\"JavaScript数组的常用方法有哪些 一、操作方法 数组基本操作可以归纳为 增、删、改、查，需要留意的是哪些方法会对原数组产生影响，哪些方法不会 下面对数组常用的操作方法做一个归纳 增 下面前三种是对原数组产生影响的增添方法，第四种则不会对原数组产生印象 push() unshift() splice() concat()\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/category/JavaScript/20.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JavaScript数组的常用方法有哪些\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"JavaScript数组的常用方法有哪些 一、操作方法 数组基本操作可以归纳为 增、删、改、查，需要留意的是哪些方法会对原数组产生影响，哪些方法不会 下面对数组常用的操作方法做一个归纳 增 下面前三种是对原数组产生影响的增添方法，第四种则不会对原数组产生印象 push() unshift() splice() concat()\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"JavaScript数组的常用方法有哪些\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"JavaScript\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-29T17:12:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JavaScript数组的常用方法有哪些\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-03-29T17:12:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":4.73,\"words\":1419},\"filePathRelative\":\"category/JavaScript/20.md\",\"localizedDate\":\"2022年3月30日\",\"excerpt\":\"<figure><figcaption>JavaScript数组的常用方法有哪些</figcaption></figure>\\n<h2> 一、操作方法</h2>\\n<hr>\\n<p>数组基本操作可以归纳为 增、删、改、查，需要留意的是哪些方法会对原数组产生影响，哪些方法不会</p>\\n<p>下面对数组常用的操作方法做一个归纳</p>\\n<p><b>增</b></p>\\n<p>下面前三种是对原数组产生影响的增添方法，第四种则不会对原数组产生印象</p>\\n<ul>\\n<li>push()</li>\\n<li>unshift()</li>\\n<li>splice()</li>\\n<li>concat()</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
