export const data = JSON.parse("{\"key\":\"v-38cd2b05\",\"path\":\"/category/%E5%85%B6%E4%BB%96/13.html\",\"title\":\"SPA(单页应用)首屏加载速度\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"SPA(单页应用)首屏加载速度\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2022-03-03T15:57:00.000Z\",\"category\":[\"其他\"],\"tag\":[\"其他\"],\"description\":\"一、什么是首屏加载 首屏时间(First Contentful Paint),指的是浏览器从响应用户输入网址地址，到首屏内容渲染完成的时间，此时整个网页不一样要全部渲染完成，但需要展示当前视窗需要的内容 首屏加载可以说是用户体验中重要的环节。 二、加载慢的原因 在页面渲染的过程，导致加载速度慢的因素可能如下： 网络延时问题 资源文件体积是否过大 资源是否重发发送请求去加载了 加载脚本的时候，渲染内容堵塞\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/%E5%85%B6%E4%BB%96/13.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"SPA(单页应用)首屏加载速度\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、什么是首屏加载 首屏时间(First Contentful Paint),指的是浏览器从响应用户输入网址地址，到首屏内容渲染完成的时间，此时整个网页不一样要全部渲染完成，但需要展示当前视窗需要的内容 首屏加载可以说是用户体验中重要的环节。 二、加载慢的原因 在页面渲染的过程，导致加载速度慢的因素可能如下： 网络延时问题 资源文件体积是否过大 资源是否重发发送请求去加载了 加载脚本的时候，渲染内容堵塞\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"SPA(单页应用)首屏加载速度\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"其他\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-03T15:57:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"SPA(单页应用)首屏加载速度\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-03-03T15:57:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.95,\"words\":884},\"filePathRelative\":\"category/其他/13.md\",\"localizedDate\":\"2022年3月3日\",\"excerpt\":\"<h2> 一、什么是首屏加载</h2>\\n<hr>\\n<p>首屏时间(First Contentful Paint),指的是浏览器从响应用户输入网址地址，到首屏内容渲染完成的时间，此时整个网页不一样要全部渲染完成，但需要展示当前视窗需要的内容</p>\\n<p>首屏加载可以说是用户体验中重要的环节。</p>\\n<h2> 二、加载慢的原因</h2>\\n<hr>\\n<p>在页面渲染的过程，导致加载速度慢的因素可能如下：</p>\\n<ul>\\n<li>网络延时问题</li>\\n<li>资源文件体积是否过大</li>\\n<li>资源是否重发发送请求去加载了</li>\\n<li>加载脚本的时候，渲染内容堵塞</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
