export const data = JSON.parse("{\"key\":\"v-54fd111c\",\"path\":\"/category/%E5%85%B6%E4%BB%96/9.html\",\"title\":\"HTTP 常见的状态码\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"HTTP 常见的状态码\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2022-03-05T15:18:00.000Z\",\"category\":[\"其他\"],\"tag\":[\"其他\"],\"description\":\"HTTP 常见的状态码 一、是什么 HTTP 状态码(英语：HTTP Status Code)，用以表示网页服务超文本传输协议响应状态的 3 为数字代码 它由 RFC2616 规范定义的，并得到RFC 2518、RFC 2817、RFC 2295、RFC 2774与 RFC 4918等规范扩展 简单来讲，http状态码的作用是服务器告诉客户端当前请求响应的状态，通过状态码就能判断和分析服务器的运行状态\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/category/%E5%85%B6%E4%BB%96/9.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"HTTP 常见的状态码\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"HTTP 常见的状态码 一、是什么 HTTP 状态码(英语：HTTP Status Code)，用以表示网页服务超文本传输协议响应状态的 3 为数字代码 它由 RFC2616 规范定义的，并得到RFC 2518、RFC 2817、RFC 2295、RFC 2774与 RFC 4918等规范扩展 简单来讲，http状态码的作用是服务器告诉客户端当前请求响应的状态，通过状态码就能判断和分析服务器的运行状态\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"HTTP 常见的状态码\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"其他\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-05T15:18:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"HTTP 常见的状态码\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-03-05T15:18:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":5.44,\"words\":1632},\"filePathRelative\":\"category/其他/9.md\",\"localizedDate\":\"2022年3月5日\",\"excerpt\":\"<figure><figcaption>HTTP 常见的状态码</figcaption></figure>\\n<h2> 一、是什么</h2>\\n<hr>\\n<p>HTTP 状态码(英语：HTTP Status Code)，用以表示网页服务超文本传输协议响应状态的 3 为数字代码</p>\\n<p>它由 RFC2616 规范定义的，并得到<code>RFC 2518</code>、<code>RFC 2817</code>、<code>RFC 2295</code>、<code>RFC 2774</code>与 <code>RFC 4918</code>等规范扩展</p>\\n<p>简单来讲，<code>http</code>状态码的作用是服务器告诉客户端当前请求响应的状态，通过状态码就能判断和分析服务器的运行状态</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
