export const data = JSON.parse("{\"key\":\"v-943e09d8\",\"path\":\"/category/HTML/1.html\",\"title\":\"8个你可能不知道的 HTML 实用技巧\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"8个你可能不知道的 HTML 实用技巧\",\"lang\":\"zh-CN\",\"author\":\"XXXWeii\",\"date\":\"2023-03-28T12:12:22.000Z\",\"category\":[\"HTML\"],\"tag\":[\"HTML\"],\"description\":\"今天要介绍的这些 HTML 技巧，绝对会让你大吃一惊！ 1. 使用 capture 属性打开设备摄像头 正如input标签具有email、text和password属性一样，我们也可以通过一些属性打开移动设备的摄像头以捕获图像。 那就是capture属性，属性值有两个： user用于前置摄像头 environment用于后置摄像头\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/HTML/1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"8个你可能不知道的 HTML 实用技巧\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"今天要介绍的这些 HTML 技巧，绝对会让你大吃一惊！ 1. 使用 capture 属性打开设备摄像头 正如input标签具有email、text和password属性一样，我们也可以通过一些属性打开移动设备的摄像头以捕获图像。 那就是capture属性，属性值有两个： user用于前置摄像头 environment用于后置摄像头\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"8个你可能不知道的 HTML 实用技巧\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"HTML\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-03-28T12:12:22.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"8个你可能不知道的 HTML 实用技巧\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2023-03-28T12:12:22.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.85,\"words\":554},\"filePathRelative\":\"category/HTML/1.md\",\"localizedDate\":\"2023年3月28日\",\"excerpt\":\"<p>今天要介绍的这些 HTML 技巧，绝对会让你大吃一惊！</p>\\n<h2> 1. 使用 capture 属性打开设备摄像头</h2>\\n<hr>\\n<p>正如<code>input</code>标签具有<code>email</code>、<code>text</code>和<code>password</code>属性一样，我们也可以通过一些属性打开移动设备的摄像头以捕获图像。</p>\\n<p>那就是<code>capture</code>属性，属性值有两个：</p>\\n<ul>\\n<li><code>user</code>用于前置摄像头</li>\\n<li><code>environment</code>用于后置摄像头</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
