export const data = JSON.parse("{\"key\":\"v-650dfbae\",\"path\":\"/category/Vue/1.html\",\"title\":\"使用Vue3时应避免的10个错误\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"使用Vue3时应避免的10个错误\",\"lang\":\"zh-CN\",\"date\":\"2023-05-24T00:00:00.000Z\",\"author\":\"XXXWeii\",\"category\":[\"Vue\"],\"tag\":[\"Vue\"],\"description\":\"Vue 3 已经稳定了相当长一段时间了。许多代码库都在生产环境中使用它，其他人最终都将不得不迁移到 Vue 3。我现在有机会使用它并记录了我的错误，下面这些错误你可能想要避免。 使用 Reactive 声明原始值 数据声明在过去都是非常直接的，但是现在有很多帮助函数供我们使用。目前的规则是： 使用reactive声明Object, Array, Map, Set 使用ref声明String, Number, Boolean\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/Vue/1.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"使用Vue3时应避免的10个错误\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Vue 3 已经稳定了相当长一段时间了。许多代码库都在生产环境中使用它，其他人最终都将不得不迁移到 Vue 3。我现在有机会使用它并记录了我的错误，下面这些错误你可能想要避免。 使用 Reactive 声明原始值 数据声明在过去都是非常直接的，但是现在有很多帮助函数供我们使用。目前的规则是： 使用reactive声明Object, Array, Map, Set 使用ref声明String, Number, Boolean\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"使用Vue3时应避免的10个错误\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-05-24T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"使用Vue3时应避免的10个错误\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2023-05-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":5.11,\"words\":1534},\"filePathRelative\":\"category/Vue/1.md\",\"localizedDate\":\"2023年5月24日\",\"excerpt\":\"<p>Vue 3 已经稳定了相当长一段时间了。许多代码库都在生产环境中使用它，其他人最终都将不得不迁移到 Vue 3。我现在有机会使用它并记录了我的错误，下面这些错误你可能想要避免。</p>\\n<h2> 使用 Reactive 声明原始值</h2>\\n<hr>\\n<p>数据声明在过去都是非常直接的，但是现在有很多帮助函数供我们使用。目前的规则是：</p>\\n<ul>\\n<li>使用<code>reactive</code>声明<code>Object, Array, Map, Set</code></li>\\n<li>使用<code>ref</code>声明<code>String, Number, Boolean</code></li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
