export const data = JSON.parse("{\"key\":\"v-3c4b714e\",\"path\":\"/category/Vue/10.html\",\"title\":\"Vue中动态引入图片为什么要是require，你不知道的那些事\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Vue中动态引入图片为什么要是require，你不知道的那些事\",\"lang\":\"zh-CN\",\"date\":\"2023-04-16T00:00:00.000Z\",\"author\":\"XXXWeii\",\"category\":[\"Vue\"],\"tag\":[\"Vue\"],\"description\":\"相信用过 vue 的小伙伴，肯定被面试官问过这样一个问题：在 vue 中动态的引入图片为什么要使用 require？ 有些小伙伴，可能会轻蔑一笑：呵，就这，因为动态添加 src 被当做静态资源处理了，没有进行编译，所以要加上 require， 我倒着都能背出来...... emmm... 乍一看好像说的很有道理啊，但是仔细一看，这句话说的到底是个啥？针对上面的回答，我不禁有如下几个疑问： 什么是静态资源？ 为什么动态添加的 src 会被当做的静态的资源？ 没有进行编译，是指为是什么没有被编译？ 加上 require 为什么能正确的引入资源，是因为加上 require 就能编译了？\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/Vue/10.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Vue中动态引入图片为什么要是require，你不知道的那些事\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"相信用过 vue 的小伙伴，肯定被面试官问过这样一个问题：在 vue 中动态的引入图片为什么要使用 require？ 有些小伙伴，可能会轻蔑一笑：呵，就这，因为动态添加 src 被当做静态资源处理了，没有进行编译，所以要加上 require， 我倒着都能背出来...... emmm... 乍一看好像说的很有道理啊，但是仔细一看，这句话说的到底是个啥？针对上面的回答，我不禁有如下几个疑问： 什么是静态资源？ 为什么动态添加的 src 会被当做的静态的资源？ 没有进行编译，是指为是什么没有被编译？ 加上 require 为什么能正确的引入资源，是因为加上 require 就能编译了？\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Vue中动态引入图片为什么要是require，你不知道的那些事\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-04-16T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Vue中动态引入图片为什么要是require，你不知道的那些事\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2023-04-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":13.26,\"words\":3979},\"filePathRelative\":\"category/Vue/10.md\",\"localizedDate\":\"2023年4月16日\",\"excerpt\":\"<p>相信用过 vue 的小伙伴，肯定被面试官问过这样一个问题：<strong>在 vue 中动态的引入图片为什么要使用 require？</strong></p>\\n<p>有些小伙伴，可能会轻蔑一笑：呵，就这，<strong>因为动态添加 src 被当做静态资源处理了，没有进行编译，所以要加上 require，</strong> 我倒着都能背出来......</p>\\n<p>emmm... 乍一看好像说的很有道理啊，但是仔细一看，这句话说的到底是个啥？针对上面的回答，我不禁有如下几个疑问：</p>\\n<ol>\\n<li>什么是静态资源？</li>\\n<li>为什么动态添加的 src 会被当做的静态的资源？</li>\\n<li>没有进行编译，是指为是什么没有被编译？</li>\\n<li>加上 require 为什么能正确的引入资源，是因为加上 require 就能编译了？</li>\\n</ol>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
