export const data = JSON.parse("{\"key\":\"v-576736b6\",\"path\":\"/category/Vue/5.html\",\"title\":\"用Vue开发的前端项目如何部署到window系统的Nginx服务器上,只需简单五步\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"用Vue开发的前端项目如何部署到window系统的Nginx服务器上,只需简单五步\",\"lang\":\"zh-CN\",\"date\":\"2022-10-15T17:09:00.000Z\",\"author\":\"XXXWeii\",\"category\":[\"Vue\",\"Nginx\"],\"tag\":[\"Vue\",\"Nginx\"],\"description\":\"1.在 nginx 官网下载稳定版本的 nginx 地址：http://nginx.org/en/download.html 参考下图： 2.nginx 安装包解压路径中不能含有中文，否则 nginx 启动会报错\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/category/Vue/5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"用Vue开发的前端项目如何部署到window系统的Nginx服务器上,只需简单五步\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1.在 nginx 官网下载稳定版本的 nginx 地址：http://nginx.org/en/download.html 参考下图： 2.nginx 安装包解压路径中不能含有中文，否则 nginx 启动会报错\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"用Vue开发的前端项目如何部署到window系统的Nginx服务器上,只需简单五步\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"XXXWeii\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Nginx\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-10-15T17:09:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"用Vue开发的前端项目如何部署到window系统的Nginx服务器上,只需简单五步\\\",\\\"image\\\":[\\\"https://github.com/XXXWeii/vuepress2-myblog/vuepress2-myblog/\\\"],\\\"datePublished\\\":\\\"2022-10-15T17:09:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"XXXWeii\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.03,\"words\":608},\"filePathRelative\":\"category/Vue/5.md\",\"localizedDate\":\"2022年10月16日\",\"excerpt\":\"<h2> 1.在 nginx 官网下载稳定版本的 nginx 地址：<a href=\\\"http://nginx.org/en/download.html\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://nginx.org/en/download.html</a> 参考下图：</h2>\\n<hr>\\n<figure><figcaption></figcaption></figure>\\n<h2> 2.nginx 安装包解压路径中不能含有中文，否则 nginx 启动会报错</h2>\\n<hr>\\n<figure><figcaption></figcaption></figure>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
